### ISSUE TITLE
[Question] 我生成了 jwt的token，增加了exp时间。  加在nginx的header里面proxy_set_header Authorization "Bearer xxx"; Authoriztion没有生效

### ISSUE THREAD

**Issue by xudingjun3131** [1Panel-dev/KubePi#268]
我生成了 jwt的token，增加了exp时间。  加在nginx的header里面proxy_set_header Authorization "Bearer xxx";
Authoriztion没有生效，登录还是需要登录，然后登录后，会有很多502报错。

[HTTP Server] http: panic serving 192.168.0.89:35840: interface conversion: interface {} is nil, not *session.UserProfile
goroutine 57657 [running]:
net/http.(*conn).serve.func1()
        net/http/server.go:1903 +0xbe
panic({0x22f4de0?, 0xc002d90b40?})
        runtime/panic.go:770 +0x132
github.com/KubeOperator/kubepi/internal/api/v1.AddV1Route.authHandler.func3(0xc007da0000)
        github.com/KubeOperator/kubepi/internal/api/v1/v1.go:62 +0x23f
github.com/kataras/iris/v12/context.(*Context).Next(0xc0002dc4d0?)
        github.com/kataras/iris/v12@v12.2.1/context/context.go:683 +0x4d
github.com/KubeOperator/kubepi/internal/api/v1.WarpedJwtHandler.func2(0xc007da0000)
        github.com/KubeOperator/kubepi/internal/api/v1/v1.go:413 +0x55
github.com/kataras/iris/v12/context.(*Context).Next(0xc007da0000?)
        github.com/kataras/iris/v12@v12.2.1/context/context.go:683 +0x4d
github.com/KubeOperator/kubepi/internal/api/v1.AddV1Route.pageHandler.func2(0xc007da0000)
        github.com/KubeOperator/kubepi/internal/api/v1/v1.go:109 +0x117
github.com/kataras/iris/v12/context.(*Context).Next(0x264ee6c?)
        github.com/kataras/iris/v12@v12.2.1/context/context.go:683 +0x4d
github.com/KubeOperator/kubepi/internal/api/v1.AddV1Route.langHandler.func1(0xc007da0000)
        github.com/KubeOperator/kubepi/internal/api/v1/v1.go:87 +0x135
github.com/kataras/iris/v12/context.(*Context).Next(0x25fe7a0?)
        github.com/kataras/iris/v12@v12.2.1/context/context.go:683 +0x4d
github.com/KubeOperator/kubepi/internal/server.(*KubePiServer).bootstrap.(*KubePiServer).setResultHandler.func1(0xc007da0000)
        github.com/KubeOperator/kubepi/internal/server/server.go:163 +0x1c
github.com/kataras/iris/v12/context.(*Context).Next(0xc0002dc4d0?)
        github.com/kataras/iris/v12@v12.2.1/context/context.go:683 +0x4d
github.com/KubeOperator/kubepi/internal/server.(*KubePiServer).setUpSession.(*Sessions).Handler.func1(0xc007da0000)
        github.com/kataras/iris/v12@v12.2.1/sessions/sessions.go:187 +0x6f
github.com/kataras/iris/v12/context.(*Context).Do(...)
        github.com/kataras/iris/v12@v12.2.1/context/context.go:531
github.com/kataras/iris/v12/core/router.(*routerHandler).HandleRequest(0xc001b57e00, 0xc007da0000)
        github.com/kataras/iris/v12@v12.2.1/core/router/handler.go:465 +0x383
github.com/kataras/iris/v12/core/router.(*Router).BuildRouter.(*Router).buildMainHandler.func1({0x5437fc0?, 0xc000484460?}, 0x499f6f?)
        github.com/kataras/iris/v12@v12.2.1/core/router/router.go:103 +0x59
github.com/kataras/iris/v12/core/router.(*Router).ServeHTTP(0x46bbf9?, {0x5437fc0?, 0xc000484460?}, 0xc0018dab68?)
        github.com/kataras/iris/v12@v12.2.1/core/router/router.go:343 +0x2a
net/http.serverHandler.ServeHTTP({0xc002d909f0?}, {0x5437fc0?, 0xc000484460?}, 0x6?)
        net/http/server.go:3142 +0x8e
net/http.(*conn).serve(0xc004422630, {0x5448b48, 0xc001d460c0})
        net/http/server.go:2044 +0x5e8
created by net/http.(*Server).Serve in goroutine 1
        net/http/server.go:3290 +0x4b4

**Comment by xudingjun3131** [comment]
再次补充，使用postman加上Authorization "Bearer xxx";调用正常。
在nginx里面加上proxy_set_header Authorization "Bearer xxx";就是不生效。还是需要再次登录，且登陆后部分接口502错误。

**Comment by xudingjun3131** [comment]
解决了。  有个sessions的会话有get和post的区别。get必须带上cookie
